# Generated by Django 5.0.1 on 2024-01-30 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0002_siteconfig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteconfig',
            options={'verbose_name': 'Site Config', 'verbose_name_plural': 'Site Config'},
        ),
        migrations.AddField(
            model_name='menulink',
            name='site_config',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='site_setup.siteconfig'),
        ),
    ]
