# Generated by Django 5.0.1 on 2024-01-31 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0003_alter_siteconfig_options_menulink_site_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='favicon',
            field=models.ImageField(blank=True, default='', upload_to='assets/favicon/%Y/%m/'),
        ),
    ]
