# Generated by Django 5.0.1 on 2024-02-06 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0005_alter_siteconfig_favicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menulink',
            name='site_config',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='site_setup.siteconfig'),
        ),
    ]
